# Generated by Django 5.1.5 on 2025-01-24 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperature',
            old_name='gpu_temp',
            new_name='battery_temp',
        ),
    ]
