# Generated by Django 5.1.5 on 2025-01-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_rename_gpu_temp_temperature_battery_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='predicted_battery_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperature',
            name='predicted_cpu_temp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
