# Generated by Django 5.1.5 on 2025-01-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_temperature_predicted_battery_temp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='battery_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='cpu_temp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
