# Generated by Django 5.1.5 on 2025-01-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_alter_temperature_battery_temp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('predicted_cpu_temp', models.FloatField()),
                ('predicted_battery_temp', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='predicted_battery_temp',
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='predicted_cpu_temp',
        ),
        migrations.AlterField(
            model_name='temperature',
            name='battery_temp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='cpu_temp',
            field=models.FloatField(),
        ),
    ]
